# Generated by Django 5.1 on 2024-11-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], max_length=10)),
                ('fecha_turno', models.DateField()),
            ],
        ),
    ]
