# Generated by Django 5.1 on 2024-11-17 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_alter_solicitud_estado'),
        ('turnos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitud'),
        ),
    ]
