# Generated by Django 5.1 on 2024-11-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Profesional', 'Profesional')], max_length=20),
        ),
    ]
